fos_rest:
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  param_fetcher_listener: true
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
    mime_types:
      json: ['application/json', 'application/x-json']
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
      - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
# exception:
#    enabled: true
#    codes:
#      { RestBundle\Exception\ResourceValidationException: 400, \Exception: 500 }
#    messages:
#      { RestBundle\Exception\ResourceValidationException: true }
  versioning:
    enabled: true
    resolvers:
      media_type: # Accept header
        enabled: true
        regex: '/(v|version)=(?P<version>[0-9\.]+)/'
